chart/urls.py
from django.conf.urls import url
 
from . import views
 
app_name = 'chart'
urlpatterns = [
    url(r'^contact/$', views.feedback_form, name='feedback_form'),
]

charts/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as authviews

from .views import (BarChartView, Boosting, BoostingGradientView, ChartData,
                    HomeView, StatCharView, get_data,main,manual,PlotData,PlotCharView, ChartEncoderData)

urlpatterns = [
    url(r'^$', main, ),
    url(r'^tsne/$', get_data, name='tsne'),
    url(r'^api/chart/$', HomeView.as_view(), name='api-data'),
    url(r'^api/chart/data/$', ChartData.as_view()),
    url(r'^api/chart_encoder/data/$', ChartEncoderData.as_view()),
    url(r'^plots/api/plot/data/$', PlotData.as_view(),name='api-plot'),
    url(r'^api/boosting/data$', Boosting.as_view()),
    url(r'^boosting$', BoostingGradientView.as_view(), name='boosting'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', authviews.login,
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', authviews.logout,
        {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^stat/$', StatCharView.as_view(), name='stat'),
    url(r'^plots/$', PlotCharView.as_view(), name='plots'),
    url(r'^bar/$', BarChartView.as_view(), name='bar'),
    url(r'^manual/$', manual, name='manual'),
    url(r'^', include('chart.urls')),


]

chart/models.py
from django.db import models

# Create your models here.
class Recomendation(models.Model):
    name = models.CharField(max_length=264,unique=True)
    lowerValue = models.IntegerField(unique=True)
    upperValue = models.IntegerField(unique=True)

    def __str__(self):
        return self.name
class Message(models.Model):
    name = models.CharField(max_length=120)
 
    def __str__(self):
        return self.name
 
 
class Feedback(models.Model):
    customer_name = models.CharField(max_length=120)
    email = models.EmailField()
    theme = models.ForeignKey(Message)
    details = models.TextField()
    date = models.DateField(auto_now_add=True)
 
    def __str__(self):
        return self.customer_name

chart/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []

chart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
 
from .forms import FeedbackForm
 
 
def feedback_form(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            form = FeedbackForm()
            return render(request, 'feedback_form.html', {'form': form})
    else:
        form = FeedbackForm()
    return render(request, 'feedback_form.html', {'form': form})

charts/views.py
import tensorflow
from keras.layers import Input, Dense
from keras.models import Model
from keras import backend as K
import datetime
import pickle
import sqlite3 as lite
import os
import numpy as np
import pandas as pd
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View
from sklearn.manifold import TSNE
from sklearn.preprocessing import MinMaxScaler

import xgboost as xgb
from rest_framework.response import Response
from rest_framework.views import APIView



User = get_user_model()


def get_data(request, *args, **kwargs):
    return render(request, 'parametrs.html')


def manual(request, *args, **kwargs):
    return render(request, 'manual.html')


def main(request, *args, **kwargs):
    return render(request, 'main.html')


class StatCharView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'stat-char.html')

class PlotCharView(View):
    def get(self, request, *args, **kwargs):
        if request.method == "GET":
            web_url = request.GET.get('group')
            defect_url = request.GET.get('defect')
            print(web_url)
            with open('fileplots.pickle', 'wb') as handle:
                pickle.dump(web_url, handle, protocol=pickle.HIGHEST_PROTOCOL)
            with open('defectplots.pickle', 'wb') as defe:
                pickle.dump(defect_url, defe, protocol=pickle.HIGHEST_PROTOCOL)
        return render(request, 'plot-char.html')

class BarChartView(View):
        def get(self, request, *args, **kwargs):
            return render(request, 'chartbar.html')


class HomeView(View):
    def get(self, request, *args, **kwargs):
        if request.method == "GET":
            web_url = request.GET.getlist('groups[]')
            defect_url = request.GET.getlist('defect[]')
            with open('filetechnicalspecifications.pickle', 'wb') as handle:
                pickle.dump(web_url, handle, protocol=pickle.HIGHEST_PROTOCOL)
            with open('filedefect.pickle', 'wb') as defe:
                pickle.dump(defect_url, defe, protocol=pickle.HIGHEST_PROTOCOL)
            print(web_url)
            print(defect_url)
        return render(request, 'charts.html', {"groups": web_url, "defect": defect_url})


class ChartEncoderData(APIView):
    authentication_classes = []
    permission_classes = []

    def autoencoder(self):
        con = lite.connect('test.db', isolation_level='DEFERRED')
        parameters_tech = ['date']
        with con:
            cur = con.cursor()

            with open('filetechnicalspecifications.pickle', 'rb') as handle:
                list_parameters = pickle.load(handle)
            list_tech_id = list(map(int, list_parameters))
            print(list_tech_id)
            print(len(list_parameters))

            with open('filedefect.pickle', 'rb') as defe:
                list_defects = pickle.load(defe)
            for i, item in enumerate(list_defects):
                list_defects[i] = int(item)
            list_tech_id.append(*list_defects)
            print(*list_defects)
            print(list_tech_id)

            #list_tech_id = [50, 51, 102, 138, 145, 151, 170, 203, 318];
            questionmarks = '?' * len(list_tech_id);
            query = 'SELECT * FROM PARAMETERS WHERE PARAMETERS.rowid IN ({})'.format(','.join(questionmarks))
            query_args = list_tech_id
            cur.execute(query, query_args)
            rows = cur.fetchall()  # извлечь данные
            for row in rows:
                parameters_tech.append(row[0])
        # print(parameters_tech)

        a = datetime.datetime(2015, 5, 17, 5, 0, 0)
        cur = con.cursor()
        query = ''
        query += 'SELECT date, '
        for row_id in list_tech_id:
            if (list_tech_id[len(list_tech_id) - 1] != row_id):
                query += 'MAX(CASE MEASUREMENTS.parameter_id WHEN ' + str(
                    row_id) + ' THEN MEASUREMENTS.value ELSE NULL END), '
            else:
                query += 'MAX(CASE MEASUREMENTS.parameter_id WHEN ' + str(
                    row_id) + ' THEN MEASUREMENTS.value ELSE NULL END)'
        query += 'FROM measurements WHERE datetime(date) < datetime(?) group by date'
        # print(query)
        cur.execute(query, (a,));
        df_query = pd.DataFrame.from_records(data=cur.fetchall(),
                                             columns=parameters_tech)  # перевод в матричный вид для pandas

        df_query.dropna(axis=0, inplace=True)  # для обработки нулевых значений, удаление строк


        print(df_query.columns)
        print(list_defects[0])
        with con:
            cur = con.cursor()
            queryName = "SELECT PARAMETERS.parameter_name FROM PARAMETERS WHERE PARAMETERS.rowid = {}".format(
                *list_defects)
            cur.execute(queryName);
            defectParameter = cur.fetchone()[0];


        sc = MinMaxScaler(feature_range=(0, 1))

        df_data = df_query.drop([defectParameter, 'date'], axis=1)
        train_x = sc.fit_transform(df_data.values)

       # training_y = sc.fit_transform(df_query[defectParameter].values)
        df_classify = df_query[defectParameter].apply(self.classifyQualityValue)
        np.random.seed(182)

        encoding_dim = 2
        input_in = Input(shape=(len(list_parameters), ))  # this is our input placeholder #list_parameters
        encoded = Dense(encoding_dim, activation='relu')(
            input_in)  # "encoded" is the encoded representation of the input
        decoded = Dense(len(list_parameters), activation='sigmoid')(encoded)  # "decoded" is the lossy reconstruction of the input

        autoencoder = Model(input_in, decoded)  # this model maps an input to its reconstruction
        encoder = Model(input_in, encoded)

        encoded_input = Input(shape=(encoding_dim, ))  # create a placeholder for an encoded (32-dimensional) input
        decoder_layer = autoencoder.layers[-1]  # retrieve the last layer of the autoencoder model
        decoder = Model(encoded_input, decoder_layer(encoded_input))  # create the decoder model

        autoencoder.compile(optimizer='adam', loss='mean_squared_error')
        autoencoder.fit(train_x, train_x,
                                  epochs=50,
                                  batch_size=32,
                                  shuffle=True, verbose = 0
                                  # validation_data=(train_x, train_x)
                                  )

        z = encoder.predict(train_x)
        print("hi")
        return z, df_classify

    def classifyQualityValue(self, x):
        if (x > 45):
            return 0
        else:
            return 1

    def get(self, request, format=None):
        autoencoder_output, classify = self.autoencoder()
        datas = []
        for i in autoencoder_output:
            point = {
                'x': i[0],
                'y': i[1],
                'r': 3,
            }
            datas.append(point)
        colors = []

        for i in classify:
            if i == 0:
                colors.append("#8C7D7E")  # черные
            if i == 1:
                colors.append("#F34F4F")  # красные - дефект

        qs_count = User.objects.all().count()

        data = {
                "default": datas,
                "color": colors
        }
        K.clear_session()
        return Response(data)

class BoostingGradientView(View):
    def get(self, request, *args, **kwargs):
        if request.method == "GET":
            algorithm = request.GET.get('algorithm')
            web_url = request.GET.getlist('groups[]')
            defect_url = request.GET.getlist('defect[]')
            with open('filetechnicalspecifications.pickle', 'wb') as handle:
                pickle.dump(web_url, handle, protocol=pickle.HIGHEST_PROTOCOL)
            with open('filedefect.pickle', 'wb') as defe:
                pickle.dump(defect_url, defe, protocol=pickle.HIGHEST_PROTOCOL)
                print('algorithm:' + algorithm)
                if (algorithm == '1'):
                    return render(request, 'charts.html', {"groups": web_url, "defect": defect_url})
                elif (algorithm == '2'):
                    return render(request, 'boosting.html', {"groups": web_url, "defect": defect_url})
                else:
                    return render(request, 'charts-encoder.html', {"groups": web_url, "defect": defect_url})

class PlotData(APIView):
    def plots(self):
        print('Here:')
        con = lite.connect('test.db', isolation_level='DEFERRED')
        parameters_tech = ['date']
        with con:
            cur = con.cursor()
            with open('fileplots.pickle', 'rb') as handle:
                list_parameters = pickle.load(handle)
            print(list_parameters)

            with open('defectplots.pickle', 'rb') as defe:
                list_defects = pickle.load(defe)
            print(list_defects)
            list = []
            list.append(list_parameters)
            list.append(list_defects)
            #list_tech_id = [50, 51, 102, 138, 145, 151, 170, 203, 318];
            questionmarks = '??'
            query = 'SELECT * FROM PARAMETERS WHERE PARAMETERS.rowid IN ({})'.format(
                ','.join(questionmarks))
            query_args = list_parameters
            print(query)
            cur.execute(query, list);
            rows = cur.fetchall()  # извлечь данные
            for row in rows:
                parameters_tech.append(row[0])

        a = datetime.datetime(2015, 5, 17, 5, 0, 0)
        cur = con.cursor()
        query = ''
        query += 'SELECT date, '
        query += 'MAX(CASE MEASUREMENTS.parameter_id WHEN ' + str(
                    list_parameters) + ' THEN MEASUREMENTS.value ELSE NULL END), '
        query += 'MAX(CASE MEASUREMENTS.parameter_id WHEN ' + str(
                    list_defects) + ' THEN MEASUREMENTS.value ELSE NULL END) '

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
	<!--Import Google Icon Font-->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	<link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}" />

	<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}" media="screen,projection" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/app.css' %}" media="screen,projection" />

	<title>Data Mining Alpha</title>
	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>

	<!--Navigation-->
	<nav class="light-blue lighten-1" role="navigation">
		<div class="nav-wrapper container">
			<a id="logo-container" href="/" class="brand-logo center">
				<i class="material-icons">cloud</i>Data Mining Alpha</a>
			<ul class="left">
				<li>
					<a href="#" data-target="slide-out" class="sidenav-trigger show-on-large">
						<i class="material-icons">menu</i>
					</a>
				</li>
			</ul>
	</nav>
	<ul id="slide-out" class="sidenav">
		<li>
			<div class="user-view">
				<div class="background light-blue ">
				</div>
				<a href="#user">
					<img class="circle" src="{% static 'images/avatar.png' %}">
				</a>
				<a href="#name">
					<span class="white-text name">Hi {{ user.username }}</span>
				</a>
				<a href="#email">
					<span class="white-text email">{{user.email}}</span>
				</a>
			</div>
		</li>

		<li>
			<a class="subheader">Actions</a>
		</li>

		<li>
			<div class="divider"></div>
		</li>
		<li>
			<p>
				<li>
					<a href="{% url 'stat' %}" class="modal-trigger" onclick="$('.button-collapse').sideNav('hide');">
						<i class="material-icons">graphic_eq</i>Data Graphs</a>
				</li>
			</p>
			<p>
				<li>
					<a href="{% url 'tsne' %}" class="modal-trigger" onclick="$('.button-collapse').sideNav('hide');">
						<i class="material-icons">trending_up</i>Data Mining Methods</a>
				</li>
			</p>
			<p>
				<li>
					<a href="#modal2" class="modal-trigger" onclick="$('.button-collapse').sideNav('hide');">
						<i class="material-icons">timeline</i>KPI Calculator</a>
				</li>

			</p>
			<li>
				<a class="subheader">System managment</a>
			</li>

			<li>
				<div class="divider"></div>
			</li>
			<p>
				<li>
					<a href="#modal1" class="modal-trigger" onclick="$('.button-collapse').sideNav('hide');">
						<i class="material-icons">file_upload</i>Upload</a>
				</li>

			</p>
			<p>
				<li>
					<a href="{% url 'manual' %}">
						<i class="material-icons">help</i>Help</a>
				</li>

			</p>
			<p>
				<li>
					<a href="{% url 'chart:feedback_form' %}">
						<i class="material-icons">feedback</i>Feedback</a>
				</li>

			</p>
			<p>
				<li>
					<a href="{% url 'admin:index' %}">
						<i class="material-icons">settings</i>Settings</a>
				</li>

			</p>

			<p>
				<li>
					<a href="{% url 'logout' %}">
						<i class="material-icons">exit_to_app</i>Logout</a>
				</li>

			</p>
		</li>

	</ul>
	<!--	main container-->
	<main>
		<div class="section no-pad-bot" id="index-banner">

			<div class="container">

				<!-- Upload modal Structure -->
				<div id="modal1" class="modal bottom-sheet">
					<div class="modal-content">
						<form action="#">
							<div class="file-field input-field">
								<div class="btn">
									<span>File</span>
									<input type="file" id="input">
								</div>
								<div class="file-path-wrapper">
									<input class="file-path validate" type="text">

								</div>
							</div>
						</form>
					</div>

					<div class="modal-footer">
						<a href="#!" type="submit" class="modal-action modal-close btn waves-effect waves-light view-center" id="send">SEND</a>
					</div>

				</div>
				<!-- Under development modal Structure -->
				<div id="modal2" class="modal bottom-sheet">
					<div class="modal-content">
						<h4>Under Development</h4>
					</div>

					<div class="modal-footer">
						<a href="#!" type="submit" class="modal-action modal-close btn waves-effect waves-light view-center" id="send">CLOSE</a>
					</div>

				</div>

				<div class="row" id="append">
					<div class="col s12 m12 l12 ">
						<div class="card ">
							<div class="card-content">
								{% if user.is_authenticated %} {% block content %} {% endblock %} {% else %}

								<div class="view-center">
									<h4>Welcome to the Data Mining System. Please, Log in to continue. </h4>
									<a class="waves-effect waves-light btn" href="{% url 'login' %}">
										<i class="material-icons left">send</i>Login</a>
								</div>
								{% endif %}
							</div>
						</div>
					</div>
				</div>

			</div>
	</main>
	<!--	Footer-->
	<footer class="page-footer orange">
		<div class="container">
			<div class="row">
				<div class="col l6 s12">
					<h5 class="white-text">Info</h5>
					<p class="grey-text text-lighten-4">Development of software to visualize trend charts and data on a mobile phone</p>
				</div>
			</div>
		</div>
		<div class="footer-copyright ">
			<div class="container"> Saint-Petersburg State Institute of Technology 2018</div>
		</div>
	</footer>
	<!-- Scripts -->
	<!--Import jQuery before materialize.js-->
	{% include 'base/js.html' %}
	<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/utils.js' %}"></script>
	<script>
		M.AutoInit(); 
	</script> {% block jquery %} {% endblock %} {% block script %} {% endblock %} {% comment %}

	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script> {% endcomment %} {% comment %}
	<script type="text/javascript" src="{% static 'js/papaparse.min.js' %}"></script> {% endcomment %}
	<script type="text/javascript" src="{% static 'js/app.js' %}"></script> {% comment %}
	<script type="text/javascript" src="{% static 'js/charts.js' %}"></script> {% endcomment %}
</body>

</html>

templates/base_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
	<!--Import Google Icon Font-->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}" media="screen,projection" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/app.css' %}" media="screen,projection" />
	<title>Data Mining Alpha</title>
	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" /> </head>

<body>
	<!--Navigation-->
	<nav class="light-blue lighten-1" role="navigation">
		<div class="nav-wrapper container">
			<a id="logo-container" href="#" class="brand-logo center">
				<i class="material-icons">cloud</i>Data Mining Alpha</a>
			{% comment %}
			<ul class="left">
				<li>
					<a href="#" data-activates="slide-out" class="button-collapse  show-on-large ">
						<i class="material-icons">menu</i>
					</a>
				</li>
			</ul>


			<ul id="slide-out" class="side-nav">
				<li>
					<div class="userView">
						<div class="background light-blue "> </div>
						<a href="#!user">
							<img class="circle" src="{% static 'images/avatar.png' %}">
						</a>
						<a href="#!name">
							<span class="white-text name">John Doe</span>
						</a>
						<a href="#!email">
							<span class="white-text email">SampleEmail@gmail.com</span>
						</a>
					</div>
				</li>
				<li>
					<a class="subheader">Active Diagrams</a>
				</li>
				<li>
					<p>
						<input type="checkbox" class="filled-in" id="tech" checked="checked" />
						<label for="tech">Technical Feasibility</label>
					</p>
					<p>
						<input type="checkbox" class="filled-in" id="oper" checked="checked" />
						<label for="oper">Opetational Feasibility</label>
					</p>
					<p>
						<input type="checkbox" class="filled-in" id="sps" checked="checked" />
						<label for="sps">SPS</label>
					</p>
				</li>
				<li>
					<div class="divider"></div>
				</li>
				<li>
					<p>
						<li>
							<a href="#modal1" class="modal-trigger" onclick="$('.button-collapse').sideNav('hide');">
								<i class="material-icons">file_upload</i>Upload</a>
						</li>

					</p>

					<p>
						<li>
							<a href="#!">
								<i class="material-icons">settings</i>Settings</a>
						</li>

					</p>
					<p>
						<li>
							<a href="{% url 'logout' %}" onclick="$('.button-collapse').sideNav('hide');">
								<i class="material-icons">exit_to_app</i>Logout</a>
						</li>

					</p>
				</li>

			</ul> {% endcomment %}
		</div>
	</nav>
	<!--	main container-->
	<main>
		<div class="section no-pad-bot" id="index-banner">

			<div class="container">
				<!-- Modal Structure -->

				<div class="row" id="append">

					{% if user.is_authenticated %} Hi {{ user.username }}!
					<a href="{% url 'logout' %}">logout</a>

					{% else %} {% comment %}
					<a class="waves-effect waves-light btn" href="{% url 'login' %}">
						<i class="material-icons left">send</i>login</a> {% endcomment %} {% endif %} {% block content %} {% endblock %}



				</div>

			</div>
	</main>
	<!--	Footer-->
	<footer class="page-footer orange">
		<div class="container">
			<div class="row">
				<div class="col l6 s12">
					<h5 class="white-text">Info</h5>
					<p class="grey-text text-lighten-4">Development of software to visualize trend charts and data on a mobile phone</p>
				</div>
			</div>
		</div>
		<div class="footer-copyright ">
			<div class="container"> Saint-Petersburg State Institute of Technology 2018</div>
		</div>
	</footer>
	<!-- Scripts -->
	<!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/app.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/Chart.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/papaparse.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/utils.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/charts.js' %}"></script>
</body>

</html>

templates/boosting.html
{% extends 'base.html' %} {% load staticfiles %} {% block jquery %}
<script>
    var endpoint = 'api/boosting/data';
    var defaultData = [];
    var labels = [];
    var colors = [];
    var groups = '{{groups}}'.replace(/&#39;/g, '');
    var arr = JSON.parse(groups);
    for (var i = 0; i < arr.length; i++) {
        console.log(arr[i]);
        $('.info').append(parameters[arr[i]] + ', ');
    }
    $.ajax({
        method: "GET",
        url: endpoint,

        success: function (data) {

            labels = data.labels
            defaultData = data.prediction
            realData = data.real
            $("#preloader").remove()
            setChart()

        },
        error: function (error_data) {
            console.log("error")
            console.log(error_data)
        }
    })
    function setChart() {
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels,
                ticks: {
                    autoSkip: false
                },
                datasets: [
                    {
                        label: ['Predicted value of black dots'],
                        data: defaultData,
                        backgroundColor: [
                            '#37da7e'
                        ],
                        borderColor: [
                            '#37da7e'
                        ],
                        pointRadius: 0,
                        fill: false,
                        cubicInterpolationMode: 'monotone',
                        borderWidth: 1
                    }, {
                        label: ['The real value of the black dots'],
                        data: realData,
                        borderColor: [
                            '#6D89D5'
                        ],
                        pointRadius: 0,
                        cubicInterpolationMode: 'monotone',
                        fill: false,
                        borderWidth: 1
                    }
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'Black dots',
                            fontSize: 14
                        }
                    }],
                    xAxes: [{
                        display: false,
                        scaleLabel: {
                            display: true,
                            labelString: 'Time',
                            fontSize: 14
                        }
                    }]
                }
            }
        });
    }
</script> {% endblock %} {% block content %}
<script>


</script>

<span class="card-title">Gradient Tree Boosting</span>
<div url-endpoint='{% url "api-data" %}' class='info'>Parameters Used: </div>

<div class="valign-wrapper" id="preloader">
    <div class="progress">
        <div class="indeterminate"></div>
    </div>
</div>
<canvas id="myChart"></canvas>




{% endblock content %}

templates/charts-autoencoder.html
{% extends 'base.html' %} {% load staticfiles %} {% block jquery %}
<script>
    var endpoint = '/api/chart_encoder/data/'
    var defaultData = []
    var labels = [];
    var colors = [];
    for (var i = 0; i < arr.length; i++) {
        $('.info').append(parameters[arr[i]] + ', ');
    }

    $.ajax({
        method: "GET",
        url: endpoint,
        success: function (data) {
            console.log(data)
            labels = data.labels
            defaultData = data.default
            colors = data.color
            $("#preloader").remove()
            setChart()

        },
        error: function (error_data) {
            console.log("error")
            console.log(error_data)
        }
    })
    function setChart() {
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'bubble',
            data: {
                labels: labels,
                ticks: {
                    autoSkip: false
                },
                datasets: [
                    {
                        label: ['Black dots'],
                        data: defaultData,
                        backgroundColor: colors,
                        borderColor: [
                            'rgba(255,99,132,1)'
                        ],
                        borderWidth: 1
                    }
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'The second component',
                            fontSize: 14
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'The first component',
                            fontSize: 14
                        }
                    }]
                }
            }
        });
    }
</script> {% endblock %} {% block content %}
<script>
    var groups = '{{groups}}'.replace(/&#39;/g, '');
    var arr = JSON.parse(groups);

</script>

<span class="card-title">Visualization of production data using the autoencoder neural network</span>
<div url-endpoint='{% url "api-data" %}' class='info'>Parameters Used: </div>
<div class="valign-wrapper" id="preloader">
    <div class="progress">
        <div class="indeterminate"></div>
    </div>
</div>
<canvas id="myChart"></canvas>
{% endblock content %}

templates/charts-encoder.html
{% extends 'base.html' %} {% load staticfiles %} {% block jquery %}
<script>
    var endpoint = '/api/chart_encoder/data/'
    var defaultData = []
    var labels = [];
    var colors = [];
    for (var i = 0; i < arr.length; i++) {
        $('.info').append(parameters[arr[i]] + ', ');
    }

    $.ajax({
        method: "GET",
        url: endpoint,
        success: function (data) {
            console.log(data)
            labels = data.labels
            defaultData = data.default
            colors = data.color
            $("#preloader").remove()
            setChart()

        },
        error: function (error_data) {
            console.log("error")
            console.log(error_data)
        }
    })
    function setChart() {
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'bubble',
            data: {
                labels: labels,
                ticks: {
                    autoSkip: false
                },
                datasets: [
                    {
                        label: ['Black dots'],
                        data: defaultData,
                        backgroundColor: colors,
                        borderColor: [
                            'rgba(255,99,132,1)'
                        ],
                        borderWidth: 1
                    }
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'The second component',
                            fontSize: 14
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'The first component',
                            fontSize: 14
                        }
                    }]
                }
            }
        });
    }
</script> {% endblock %} {% block content %}
<script>
    var groups = '{{groups}}'.replace(/&#39;/g, '');
    var arr = JSON.parse(groups);

</script>

<span class="card-title">Visualization of production data using the autoencoder neural network</span>
<div url-endpoint='{% url "api-data" %}' class='info'>Parameters Used: </div>
<div class="valign-wrapper" id="preloader">
    <div class="progress">
        <div class="indeterminate"></div>
    </div>
</div>
<canvas id="myChart"></canvas>
{% endblock content %}